version: '2'

services:

  db:
    image: xiaomao361/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: box
      TZ: Asia/Shanghai
    volumes:
      #- ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./data:/var/lib/mysql
    networks:
      - backend
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  box:
    build: ./txCloudBox
    restart: unless-stopped
    ports:
      - 11112:11112
    environment:
      BOX_DB_HOST: db
      BOX_DB_PASSWORD: 123456
    volumes:
      - ./dicom:/code/box/dicom
    networks:
      - backend

networks:
  backend:
    external:
      name: backend
