version: '2'
services:
  base:
    restart: unless-stopped
    build: ./
    environment:
      TZ: Asia/Shanghai
    networks:
      - backend

  app:
    restart: unless-stopped
    extends: base
    ports:
      - '5000'

  crond:
    restart: unless-stopped
    extends: base
    ports:
      - '8005:3000'
    command: entrypoint.sh crond

networks:
  backend:
    external:
      name: backend
