version: '2'
services:
  base:
    restart: unless-stopped
    build: .
    environment:
      TZ: Asia/Shanghai
    ports:
      - '3000'
    networks:
      - backend

  app:
    restart: unless-stopped
    extends: base
    environment:
      TZ: Asia/Shanghai
    ports:
      - '3000'
    networks:
      - backend

  crond:
    restart: unless-stopped
    extends: base
    environment:
      TZ: Asia/Shanghai
    command: enterpoint.sh crond
    ports:
      - '8000:3000'
    networks:
      - backend

networks:
  backend:
    external:
      name: backend
