version: '2'
services:
  base:
    restart: unless-stopped
    build: ./manager
    environment:
      TZ: Asia/Shanghai
    ports:
      - '8004:3000'
    networks:
      - backend

  app:
    restart: unless-stopped
    extends: manager_base
    ports:
      - '3000'

  crond:
    restart: unless-stopped
    extends: manager_base
    command: enterpoint.sh crond

networks:
  backend:
    external:
      name: backend
